import { expect, test } from '@playwright/test'
import type {} from './gameplay.spec'
test('courier event cooldown, collectible, waypoint and confirmed save reset',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium','Interaction scenario runs once.')
  await page.goto('/');await page.getByRole('button',{name:'New Game',exact:true}).click();await page.getByRole('button',{name:'Start exploring',exact:true}).click();await page.waitForFunction(()=>window.__breakwater?.game.getState().ready)
  await page.evaluate(()=>{const d=window.__breakwater;d.runtime.playerBody!.setTranslation({x:11,y:1.3,z:42},true);d.runtime.position=[11,1.3,42]})
  await page.waitForTimeout(300);await page.keyboard.press('KeyE')
  expect(await page.evaluate(()=>window.__breakwater.game.getState().money)).toBe(475)
  await page.keyboard.press('KeyE');expect(await page.evaluate(()=>window.__breakwater.game.getState().money)).toBe(475)
  await page.evaluate(()=>window.__breakwater.runtime.elapsed+=181)
  await page.keyboard.press('KeyE');expect(await page.evaluate(()=>window.__breakwater.game.getState().money)).toBe(600)
  await page.evaluate(()=>{const d=window.__breakwater;d.runtime.playerBody!.setTranslation({x:23,y:1.3,z:34},true);d.runtime.position=[23,1.3,34]})
  await page.waitForTimeout(300);await page.keyboard.press('KeyE')
  expect(await page.evaluate(()=>window.__breakwater.game.getState().money)).toBe(675)
  await page.keyboard.press('KeyM');await page.getByRole('button',{name:'Quayline Garage',exact:false}).click()
  expect(await page.evaluate(()=>window.__breakwater.game.getState().waypoint)).toEqual([105,.2,18])
  await page.keyboard.press('Escape');await page.getByRole('button',{name:'Save game',exact:false}).click()
  await expect(page.getByText('Progress saved.',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Return to main menu',exact:false}).click()
  await page.getByRole('button',{name:'Reset saved game',exact:true}).click();await page.getByRole('button',{name:'Keep save',exact:true}).click()
  await expect(page.getByRole('button',{name:'Continue',exact:true})).toBeEnabled()
  await page.getByRole('button',{name:'Reset saved game',exact:true}).click();await page.getByRole('button',{name:'Delete saved game',exact:true}).click()
  await expect(page.getByRole('button',{name:'Continue',exact:true})).toBeDisabled()
  expect(await page.evaluate(()=>localStorage.getItem('breakwater.save.v1'))).toBeNull()
})
